/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conectarcuatro.vistas;

import javax.swing.JOptionPane;

/**
 *
 * @author Urrea
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton5.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("jButton1");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));

        jButton2.setText("jButton1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton3.setText("jButton1");
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, -1, -1));

        jButton4.setText("jButton1");
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, -1));

        jButton6.setText("jButton1");
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, -1));

        jButton7.setText("jButton1");
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, -1));

        jButton8.setText("jButton1");
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, -1));

        jButton9.setText("jButton1");
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        jButton10.setText("jButton1");
        jPanel2.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jButton11.setText("jButton1");
        jPanel2.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jButton12.setText("jButton1");
        jPanel2.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jButton13.setText("jButton1");
        jPanel2.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jButton14.setText("jButton1");
        jPanel2.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jButton15.setText("jButton1");
        jPanel2.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        jButton16.setText("jButton1");
        jPanel2.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        jButton17.setText("jButton1");
        jPanel2.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));

        jButton18.setText("jButton1");
        jPanel2.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jButton19.setText("jButton1");
        jPanel2.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        jButton20.setText("jButton1");
        jPanel2.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        jButton21.setText("jButton1");
        jPanel2.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        jButton22.setText("jButton1");
        jPanel2.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        jButton23.setText("jButton1");
        jPanel2.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        jButton24.setText("jButton1");
        jPanel2.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jButton25.setText("jButton1");
        jPanel2.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jButton26.setText("jButton1");
        jPanel2.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        jButton27.setText("jButton1");
        jPanel2.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        jButton28.setText("jButton1");
        jPanel2.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        jButton29.setText("jButton1");
        jPanel2.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, -1));

        jButton30.setText("jButton1");
        jPanel2.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        jButton31.setText("jButton1");
        jPanel2.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        jButton32.setText("jButton1");
        jPanel2.add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jButton33.setText("jButton1");
        jPanel2.add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        jButton34.setText("jButton1");
        jPanel2.add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        jButton35.setText("jButton1");
        jPanel2.add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        jButton36.setText("jButton1");
        jPanel2.add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jButton37.setText("jButton1");
        jPanel2.add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        jButton38.setText("jButton1");
        jPanel2.add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        jButton39.setText("jButton1");
        jPanel2.add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        jButton40.setText("jButton1");
        jPanel2.add(jButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        jButton41.setText("jButton1");
        jPanel2.add(jButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        jButton42.setText("jButton1");
        jPanel2.add(jButton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        jButton43.setText("jButton1");
        jPanel2.add(jButton43, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Holis");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
